# SPDX-FileCopyrightText: 2025 Sergio Martins
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      action-updates:
        patterns:
          - "*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      submodule-updates:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/slint"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      cargo-updates:
        patterns:
          - "*"
