// SPDX-FileCopyrightText: 2025 Sergio Martins
// SPDX-License-Identifier: MIT
export global Style {
    // Main backgrounds
    out property <color> background: #2d2e32;
    out property <color> background2: #141b28;
    out property <color> button-background: #414244;
    out property <color> button-active: #0290f6;

    // Section
    out property <color> section-background-color: #1a2332;
    out property <color> section-text-color: #ffffff;
    out property <length> section-font-size: 21px;

    // Task
    out property <color> task-text-color: #e0e0e0;
    out property <color> task-secondary-text-color: #808080;
    out property <color> task-completed-text-color: #606060;
    out property <color> task-calendar-text-disabled: #405040;
    out property <color> task-background: #3e3f43;
    out property <color> task-important-background: #f07e01;
    out property <color> task-evening-background: #484a65;
    out property <length> task-height: 82px;
    out property <length> task-evening-height: 44px;
    out property <length> task-spacing: 18px;

    // Text
    out property <color> text-color2: #98999e;
    out property <color> icon-color: #98999e;

    // Week view
    out property <length> weekday-font-size: 24px;
    out property <color> weekday-text-color: #ffffff;

    // Calendar
    out property <color> calendar-background: #222327;
    out property <color> calendar-highlight: #0290f6;
    out property <color> calendar-text: #ffffff;
    out property <color> calendar-disabled-text: #405040;
    out property <color> calendar-secondary-text: #98999e;

    // Plus button
    out property <color> plus-button-color: #0ea5e9;
    out property <length> plus-button-size: 48px;

    // Menu
    out property <length> menu-height: 52px;

    // Buttons
    out property <color> button-color: #0ea5e9;
    out property <color> button-text-color: #000000;
}
