import { Style } from "../style.slint";

export component CheckBox {
    in-out property <bool> checked: false;
    in property <bool> small-variant: false;
    callback toggled;

    property <length> sz: root.small-variant ? 18px : 26px;

    width: root.sz;
    height: root.sz;

    TouchArea {
        clicked => {
            root.checked = !root.checked;
            root.toggled();
        }
    }

    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: self.width / 2;
        background: Style.task-background;
        border-color: Style.text-color2;
        border-width: 1px;

        if root.checked: Rectangle {
            property <length> inner: root.small-variant ? 9px : 14px;
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            width: self.inner;
            height: self.inner;
            border-radius: self.width / 2;
            background: Style.text-color2;
        }
    }
}
