// SPDX-FileCopyrightText: 2025 Sergio Martins
// SPDX-License-Identifier: MIT
import { Style } from "../style.slint";

export component TagBadge {
    in property <string> name;
    in property <color> badge-color;
    in property <bool> is-selected;
    callback clicked;

    height: 32px;
    width: inner-layout.preferred-width;

    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 16px;
        background: root.badge-color;
        border-color: root.is-selected ? #ffffff : transparent;
        border-width: root.is-selected ? 2px : 0px;

        TouchArea {
            clicked => { root.clicked(); }
        }

        inner-layout := HorizontalLayout {
            padding-left: 14px;
            padding-right: 14px;

            Text {
                text: root.name;
                color: #ffffff;
                font-size: 14px;
                vertical-alignment: center;
            }
        }
    }
}
