# SPDX-FileCopyrightText: 2025 Sergio Martins
# SPDX-License-Identifier: MIT

name: pointless_core Rust Tests

on:
  push:
    paths:
      - 'slint/pointless_core/**'
      - '.github/workflows/core_rs.yml'
  pull_request:
    paths:
      - 'slint/pointless_core/**'
      - '.github/workflows/core_rs.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: slint/pointless_core
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: slint/pointless_core

      - name: Build
        run: cargo build

      - name: Test
        env:
          POINTLESS_SUPABASE_URL: ${{ secrets.POINTLESS_SUPABASE_URL }}
          POINTLESS_SUPABASE_ANON_KEY: ${{ secrets.POINTLESS_SUPABASE_ANON_KEY }}
          POINTLESS_DEBUG_USERNAME: ${{ secrets.POINTLESS_DEBUG_USERNAME }}
          POINTLESS_DEBUG_PASSWORD: ${{ secrets.POINTLESS_DEBUG_PASSWORD }}
        run: cargo test --verbose
